### ISSUE TITLE
Model.py not found

### ISSUE THREAD

**Issue by mhaut** [ZhaohuiXue/A-SPN-release#3]
Dear author,

I am trying to run your code, however, the file model.py does not exist. Would you be so kind as to publish it?

Thank you.

**Comment by ZhaohuiXue** [comment]
I will send you by email.

**Comment by ZhaohuiXue** [comment]
Tell me your email if possible.

**Comment by mhaut** [comment]
Dear author, my email is juanmariohaut@unex.es. Thank you so much.

**Comment by wzzlf** [comment]
Dear author,

I am trying to run your code, however, the file model.py does not exist. Would you be so kind as to publish it?

**Comment by ZHUYMGeo** [comment]
Dear author,

Could you please send me the model.py code? email:  2012210018@email.cugb.edu.cn

Thank you.
